name: build

on:
  push:
  pull_request:
  schedule:
    # https://crontab.guru/
    # At 12:00 AM, only on Monday
    - cron: 0 0 * * 1

env:
  build-folder: build
  python-version: 3.9

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: Windows MSVC 19.29 x86 64 Debug Static
            os: windows-latest
            compiler: msvc
            arch: x86_64
            build_type: Debug
            runtime: static
            runtime_type: Debug

          - name: Windows MSVC 19.29 x86 64 RelWithDebInfo Static
            os: windows-latest
            compiler: msvc
            arch: x86_64
            build_type: RelWithDebInfo
            runtime: static
            runtime_type: Release

          - name: Windows MSVC 19.29 ARM v8 Debug Dynamic
            os: windows-latest
            compiler: msvc
            arch: armv8
            build_type: Debug
            runtime: dynamic
            runtime_type: Debug

          - name: Windows MSVC 19.29 ARM v8 RelWithDebInfo Dynamic
            os: windows-latest
            compiler: msvc
            arch: armv8
            build_type: RelWithDebInfo
            runtime: dynamic
            runtime_type: Release

          - name: Windows Clang 12 x86 64 Debug MTd
            os: windows-latest
            compiler: clang
            version: 13
            arch: x86_64
            build_type: Debug
            runtime: MTd

          - name: Windows Clang 12 x86 64 RelWithDebInfo MT
            os: windows-latest
            compiler: clang
            version: 13
            arch: x86_64
            build_type: RelWithDebInfo
            runtime: MT

          - name: Windows Clang 12 ARM v8 Debug MDd
            os: windows-latest
            compiler: clang
            version: 13
            arch: armv8
            build_type: Debug
            runtime: MDd

          - name: Windows Clang 12 ARM v8 RelWithDebInfo MD
            os: windows-latest
            compiler: clang
            version: 13
            arch: armv8
            build_type: RelWithDebInfo
            runtime: MD

          - name: Ubuntu GCC x86 64 Debug
            os: ubuntu-latest
            compiler: gcc
            arch: x86_64
            build_type: Debug

          - name: Ubuntu GCC x86 64 RelWithDebInfo
            os: ubuntu-latest
            compiler: gcc
            arch: x86_64
            build_type: RelWithDebInfo

          - name: Ubuntu GCC ARM v8 Debug
            os: ubuntu-latest
            compiler: gcc
            arch: armv8
            build_type: Debug

          - name: Ubuntu GCC ARM v8 RelWithDebInfo
            os: ubuntu-latest
            compiler: gcc
            arch: armv8
            build_type: Debug

          - name: Ubuntu Clang x86 64 Debug
            os: ubuntu-latest
            compiler: clang
            arch: x86_64
            build_type: Debug

          - name: Ubuntu Clang x86 64 RelWithDebInfo
            os: ubuntu-latest
            compiler: clang
            arch: x86_64
            build_type: RelWithDebInfo

          - name: Ubuntu Clang ARM v8 Debug
            os: ubuntu-latest
            compiler: clang
            arch: armv8
            build_type: Debug

          - name: Ubuntu Clang ARM v8 RelWithDebInfo
            os: ubuntu-latest
            compiler: clang
            arch: armv8
            build_type: Debug

          - name: OS X Apple Clang x86 64 Debug
            os: macos-latest
            compiler: apple-clang
            arch: x86_64
            build_type: Debug

          - name: OS X Apple Clang x86 64 RelWithDebInfo
            os: macos-latest
            compiler: apple-clang
            arch: x86_64
            build_type: RelWithDebInfo

          - name: OS X Apple Clang ARM v8 Debug
            os: macos-latest
            compiler: apple-clang
            arch: armv8
            build_type: Debug

          - name: OS X Apple Clang ARM v8 RelWithDebInfo
            os: macos-latest
            compiler: apple-clang
            arch: armv8
            build_type: RelWithDebInfo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install requirements
        run: python -m pip install --upgrade pip conan

      - name: Install dependencies
        run: conan install . -if ${{ env.build-folder }} --build outdated
          -pr .conan/profiles/profile.jinja -pr:b .conan/profiles/profile.jinja
        env:
          Compiler: ${{ matrix.config.compiler }}
          Version: ${{ matrix.config.version }}
          Arch: ${{ matrix.config.arch }}
          BuildType: ${{ matrix.config.build_type }}
          Toolset: ${{ matrix.config.toolset }}
          Runtime: ${{ matrix.config.runtime }}
          RuntimeType: ${{ matrix.config.runtime_type }}
          Tests: 'True'

      - name: Build
        run: conan build . -bf ${{ env.build-folder }}

      - name: Test
        run: ctest -C ${{ matrix.config.build_type }}
          --output-on-failure
          --repeat-until-fail 1
          --test-dir ${{ env.build-folder }}
          --output-junit report.xml
          --timeout 120
